### ISSUE TITLE
「Ruby/GObjectIntrospection」の表記の統一

### ISSUE THREAD

**Issue by kou** [shiro615/ruby-grant-2018#1]
ライブラリー名は「Ruby/GObjectIntrospection」（空白なし）https://github.com/ruby-gnome2/ruby-gnome2/tree/master/gobject-introspection なんで、それに統一するか「gobject-introspection gem」に統一するかどっちがよさそうです！

後者の方がわかりやすいかも。

**Comment by shiro615** [comment]
ライブラリー名は `gobject-introspection gem` に統一しました！
https://github.com/shiro615/ruby-grant-2018/commit/e523682e5bd24078742613a3fa238705bbf3ce23

**Comment by kou** [comment]
さすがです！
