### ISSUE TITLE
現在の課題の整理

### ISSUE THREAD

**Issue by kou** [shiro615/ruby-grant-2018#2]
> GObject Introspectionを使ったバインディング開発には以下の課題があります。

パフォーマンス面で課題があります、と、今回はパフォーマンスについて取り組みますというのを明確にしたほうがいいかも！

「手書きより遅い」と「オーバーヘッドがある」は同じ（パフォーマンス面で課題がある）なのでサブ項目だけでよいと思います。

サブ項目ですが、「動的な引数の変換」は言いたいことは私にはわかるんですがgobject-introspection gemをよく知らない人には伝わらなそうです。補足説明として「手書きのバインディングでは1番目の引数は文字列として変換するというように書けるが、gobject intorspection gemは実行時に1番目の引数の型情報を取得してその情報を元に変換する。そのため、実行時に適切な変換方法を確定するためのコストがかかる。」みたいなのがあった方がいいんじゃないかと思いました。

「libffiを使った関数呼び出し」も少し補足があったほうがいいかも！手書きのバインディングとlibffiを使ったバインディングでこのくらいオーバヘッドがあります、みたいなやつ。

https://github.com/kou/rabbit-slide-kou-rubykaigi-2016 に私が作ったバインディング（手書きのやつとかFiddle（libffiを使っている）を使ったやつとかffi gem（libffiを使っている）を使ったやつとか）があるので、それを使えばすぐにデータを出せるはず。

**Comment by shiro615** [comment]
`動的な引数の変換` と `libffiを使った関数呼び出し` に補足をつけました！
https://github.com/shiro615/ruby-grant-2018/commit/6a49baff331f014e0d9dafe20d0094ad003ea623

**Comment by kou** [comment]
数値が入ってそれっぽさが増えましたね！
