### ISSUE TITLE
なぜやるかを追記

### ISSUE THREAD

**Issue by kou** [shiro615/ruby-grant-2018#3]
https://www.ruby.or.jp/ja/news/20180801#%E6%8F%90%E6%A1%88%E3%81%AE%E5%BF%9C%E5%8B%9F%E6%96%B9%E6%B3%95 応募項目になんでこのプロジェクトをやるのかを書く項目がないんですね。「プロジェクトの詳細」に書くといいのかしら。

gobject-introspection gemのメリットは次の3点です。

* RubyっぽいAPIを自動生成できる
  * SWIGはC++ならできる（ことがある）
  * SWIGはCでもユーザーが設定ファイルを頑張って書けばできるが、ライブラリー毎に作らないといけない
  * libffi/Fiddleは自動生成できない
  * 手書きは自動生成できない
* Ruby以外の言語バインディングも自動生成できる
  * SWIGもできる
  * 他の言語の開発者とも協力できる
* 実行時に言語バインディングを自動生成できる
  * SWIGはできない
  * ライブラリーを更新しても言語バインディングを更新する必要はない

ただし、パフォーマンス面で課題があるのでそれを解決できると↑に「速い」が加わる。

**Comment by shiro615** [comment]
プロジェクトの詳細になぜこのプロジェクトをやるのかの説明を追記しました！
https://github.com/shiro615/ruby-grant-2018/commit/95fe77d6d7eed9843e78df55e9c1be87d6cf9b1f

**Comment by kou** [comment]
さすがです！
